runtime: python
env: flex
entrypoint: gunicorn -b $PORT calls:app
inbound_services:

runtime_config:
    python_version: 7
manual_scaling:
    instances: 1
resources:
    cpu: 1
    memory_gb: 0.5
    disk_size_gb: 10

#env_variables:
  #ACCOUNT_SID: "AC4e526418563676fed44ab3a8815e6d25"
  #AUTH_TOKEN: "8dfc38f919ef11571b0ce74660c2c50f"

handlers:
# Matches requests to /images/... to files in static/images/...
# - url: /images
#  static_dir: static/images

- url: /static
  static_dir: static

- url: /.*
  script: auto
